### ISSUE TITLE
Playing a MIDI file completely caused a crash of the app while the playback continued

### ISSUE THREAD

**Issue by dharasim** [DCMLab/MIDFT#23]
This happened in the meeting on Monday, November 15th, 2021.
I think the issue was related to an out-of-bounds access to some array.

**Comment by heyGio** [comment]
Should be fixed now!

**Comment by fabianmoss** [comment]
I still have this error, even when I upload very short midi files (~30 sec)

**Comment by heyGio** [comment]
I'm sorry, I committed the fix but didn't re-deploy the changes on github Pages. Now they are lined up! Let me know if it works now @fabianmoss

**Comment by fabianmoss** [comment]
Yes it seems to work, great!
